### PR TITLE
update for V2024.05 release

### PR DESCRIPTION
**Pull request by arnopo**
Update the zephyr version and point to the v2024.05 release candidate

### CODE REVIEW

**Review by tnmysh — APPROVED** [review]
Tested rpmsg_multi_service demo on zcu102 qemu.
Tested RPMSG TTY, and RPMSG SAMPLE CLIENT and it's passing.
Approved.

**Comment by wmamills** [comment]
@arnopo  This needs to be split into two.  The update to Zephyr 3.6 should be done in main and the lock to v2024.05 should be done in the v2024.05 branch.  I will cherry pick these to do this.

**Comment by arnopo** [comment]
> @arnopo This needs to be split into two. The update to Zephyr 3.6 should be done in main and the lock to v2024.05 should be done in the v2024.05 branch. I will cherry pick these to do this.

zephyr update available in https://github.com/OpenAMP/openamp-system-reference/pull/46
I will update this one to remove it

**Comment by arnopo** [comment]
@wmamills 
I also updated the openamp version to v2024.05.1. The PR still point to the main, should we create the v2024.05 branch?

**Comment by wmamills** [comment]
I am waiting to create the v2024.05 branch until I have tested and landed any new commits.  Last time I created the branch early and had to duplicate commits to both branches.  I would prefer to minimize that.

**Comment by wmamills** [comment]
@arnopo please re-target this PR to the v2024.05 branch and then go ahead and merge it.

**Pull request merged**
