### PR TITLE
Move apps dir from the open-amp repository

### PR DESCRIPTION
**Pull request by kernelchuk**
My first attempt to move the apps based on our discussions about libmetal examples. Please, see: https://github.com/OpenAMP/libmetal/pull/231.

### CODE REVIEW

**Comment by tnmysh** [comment]
> @wmamills, @edmooring, @tnmysh, @glneo:
> 
> This PR simply moves the application folder from the library, which I believe is a step in the right direction.
> 
> As we have rejected #15, I want first to confirm that everyone is okay with this PR.
> 
> The middle -term objectives (from my point of view) is to:
> 
> * First, clean up libraries by removing applications and tests (which is the objective of this PR).
> * Second, enhance the baremetal/FreeRtos  applications to support non-AMD platforms.
> 
> Is everyone is Ok with that plan?

Thanks @arnopo, I am okay with this plan.

**Comment by kernelchuk** [comment]
Hi @arnopo, @wmamills, @edmooring, @glneo:

I have been up-streaming AMD’s internal commits to achieve the “upstream first” status, i.e., our internal forks have minimum divergence from the GitHub. The largest delta is in the apps and the examples, which are frozen in OpenAMP (see https://github.com/OpenAMP/libmetal/pull/23) pending the move to this repo.

@arnopo posted two objectives. The first one is clear and easy to understand. I think the second objective should be a community effort, i.e.: the example code grandfathered in the first step will have to adopt a new common/platform-specific framework. This framework is yet to be defined.

My management approves my work to:
1. Move the examples:
    - https://github.com/OpenAMP/openamp-system-reference/pull/19
    - https://github.com/OpenAMP/openamp-system-reference/pull/21
2. Convert them to the new common framework when it’s defined by the community.

Can we, please, clarify if the second objective (_support non-AMD platforms_) is or is-not a precondition to the move?

**Comment by arnopo** [comment]
> Hi @arnopo, @wmamills, @edmooring, @glneo:
> 
> I have been up-streaming AMD’s internal commits to achieve the “upstream first” status, i.e., our internal forks have minimum divergence from the GitHub. Our largest delta is in the examples, which are frozen in OpenAMP (see [OpenAMP/libmetal#23](https://github.com/OpenAMP/libmetal/pull/23)) pending the move to this repo.
> 
> @arnopo posted two objectives. The first one is clear and easy to understand. I think the second objective should be a community effort, i.e.: the example code grandfathered in the first step will have to adopt a new common/platform-specific framework. This framework is yet to be defined.
> 
> My management approves my work to:
> 
> 1. Move the examples:
>    
>    * [Move apps dir from the open-amp repository #19](https://github.com/OpenAMP/openamp-system-reference/pull/19)
>    * [Move examples dir from the libmetal repository #21](https://github.com/OpenAMP/openamp-system-reference/pull/21)
> 2. Convert them to the new common framework when it’s defined by the community.
> 
> Can we, please, clarify if the second objective (_support non-AMD platforms_) is or is-not a precondition to the move?

Sorry for the delay, we are still discussing on the way we do do it. Come back to you ASAP

**Comment by wmamills** [comment]
@tnmysh I presume your PR# 44 makes this redundant.  If so please close this one.

**Comment by wmamills** [comment]
PR #44 replaces this PR

**Pull request closed without merging**
